apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"labels":{"template":"generic-java-jenkins-pipeline"},"name":"basic-spring-boot-deploy-pre-ivt","namespace":"basic-spring-boot-cicd"},"spec":{"params":[{"name":"git-revision","type":"string"}],"resources":[{"name":"basic-spring-boot-git-pre-ivt","type":"git"}],"tasks":[{"name":"maven-build-binary-build","params":[{"name":"buildConfig","value":"basic-spring-boot-cicd-pre-ivt"}],"resources":{"inputs":[{"name":"source","resource":"basic-spring-boot-git-pre-ivt"}]},"taskRef":{"name":"maven-build-binary-build"}},{"name":"helm-upgrade","params":[{"name":"helmRepo","value":"mhill.azurecr.io/helm"},{"name":"username","value":"mhill"},{"name":"password","value":"WUeQdKnivwFcGr8d3QqDrxevjvIX7IV+"},{"name":"chartName","value":"ocp-openjdk"},{"name":"releaseVersion","value":"v1"},{"name":"releaseName","value":"v1"},{"name":"releaseNamespace","value":"basic-spring-boot-pre-ivt"},{"name":"overwriteValues","value":"nameOverride=basic-spring-boot-pre-ivt,fullnameOverride=basic-spring-boot-pre-ivt"},{"name":"helmVersion","value":"latest"},{"name":"env","value":"pre-ivt"}],"resources":{"inputs":[{"name":"source","resource":"basic-spring-boot-git-pre-ivt"}]},"runAfter":["maven-build-binary-build"],"taskRef":{"name":"helm-upgrade-from-repo"}},{"name":"deploy-to-dev","params":[{"name":"fromNamespace","value":"basic-spring-boot-cicd"},{"name":"toNamespace","value":"basic-spring-boot-pre-ivt"},{"name":"tag","value":"ivtnew"},{"name":"fromImageStream","value":"basic-spring-boot-cicd-pre-ivt"},{"name":"toImageStream","value":"basic-spring-boot-pre-ivt"},{"name":"deploymentResource","value":"deploymentconfig"},{"name":"deployment","value":"basic-spring-boot-pre-ivt"}],"runAfter":["helm-upgrade"],"taskRef":{"name":"deploy"}}]}}
  generation: 1
  labels:
    template: generic-java-jenkins-pipeline
  name: basic-spring-boot-deploy-pre-ivt
  selfLink: /apis/tekton.dev/v1beta1/namespaces/basic-spring-boot-cicd/pipelines/basic-spring-boot-deploy-pre-ivt
spec:
  params:
  - name: git-revision
    type: string
  resources:
  - name: basic-spring-boot-git-pre-ivt
    type: git
  tasks:
  - name: maven-build-binary-build
    params:
    - name: buildConfig
      value: basic-spring-boot-cicd-pre-ivt
    resources:
      inputs:
      - name: source
        resource: basic-spring-boot-git-pre-ivt
    taskRef:
      kind: Task
      name: maven-build-binary-build
  - name: helm-upgrade
    params:
    - name: helmRepo
      value: mhill.azurecr.io/helm
    - name: username
      value: mhill
    - name: password
      value: WUeQdKnivwFcGr8d3QqDrxevjvIX7IV+
    - name: chartName
      value: ocp-openjdk
    - name: releaseVersion
      value: v1
    - name: releaseName
      value: v1
    - name: releaseNamespace
      value: basic-spring-boot-pre-ivt
    - name: overwriteValues
      value: nameOverride=basic-spring-boot-pre-ivt,fullnameOverride=basic-spring-boot-pre-ivt
    - name: helmVersion
      value: latest
    - name: env
      value: pre-ivt
    resources:
      inputs:
      - name: source
        resource: basic-spring-boot-git-pre-ivt
    runAfter:
    - maven-build-binary-build
    taskRef:
      kind: Task
      name: helm-upgrade-from-repo
  - name: deploy-to-dev
    params:
    - name: fromNamespace
      value: basic-spring-boot-cicd
    - name: toNamespace
      value: basic-spring-boot-pre-ivt
    - name: tag
      value: ivtnew
    - name: fromImageStream
      value: basic-spring-boot-cicd-pre-ivt
    - name: toImageStream
      value: basic-spring-boot-pre-ivt
    - name: deploymentResource
      value: deploymentconfig
    - name: deployment
      value: basic-spring-boot-pre-ivt
    runAfter:
    - helm-upgrade
    taskRef:
      kind: Task
      name: deploy
