apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{"tekton.dev/tags":"helm"},"labels":{"app.kubernetes.io/version":"0.1","template":"generic-java-jenkins-pipeline"},"name":"helm-upgrade-from-repo","namespace":"basic-spring-boot-cicd"},"spec":{"params":[{"description":"Specify a specific helm repo","name":"helmRepo"},{"description":"Username","name":"username"},{"description":"Pass","name":"password"},{"description":"Specify chart name that will be deployed","name":"chartName"},{"default":"v1.0.0","description":"The helm release version in semantic versioning format","name":"releaseVersion"},{"default":"helmRelease","description":"The helm release name","name":"releaseName"},{"default":"","description":"The helm release namespace","name":"releaseNamespace"},{"default":"","description":"Specify the values you want to overwrite, comma separated: autoscaling.enabled=true,replicas=1","name":"overwriteValues"},{"default":"latest","description":"Specify a specific helm version","name":"helmVersion"},{"default":"dev","description":"Specify what env to use for values","name":"env"}],"resources":{"inputs":[{"name":"source","type":"git"}]},"steps":[{"image":"lachlanevenson/k8s-helm:$(inputs.params.helmVersion)","name":"upgrade-from-repo","script":"echo \"setting HELM_EXPERIMENTAL_OCI=1\"\nexport HELM_EXPERIMENTAL_OCI=1\necho \"logging in to helm repo\"\nhelm registry login \"$(inputs.params.helmRepo)\" --username \"$(inputs.params.username)\" --password \"$(inputs.params.password)\"\necho \"pulling chart to local repo\"\nhelm chart pull \"$(inputs.params.helmRepo)\"/\"$(inputs.params.chartName)\":v1\necho \"exporting helm chart\"\nhelm chart export \"$(inputs.params.helmRepo)\"/\"$(inputs.params.chartName)\":v1 --destination .\necho \"installing helm chart\"\nhelm upgrade --install ocp-openjdk ./\"$(inputs.params.chartName)\" -f ./ocp/\"$(inputs.params.env)\".yaml --namespace \"$(inputs.params.releaseNamespace)\" --set \"$(inputs.params.overwriteValues)\"\n","workingDir":"/workspace/source"}]}}
    tekton.dev/tags: helm
  generation: 1
  labels:
    app.kubernetes.io/version: "0.1"
    template: generic-java-jenkins-pipeline
  name: helm-upgrade-from-repo
  selfLink: /apis/tekton.dev/v1beta1/namespaces/basic-spring-boot-cicd/tasks/helm-upgrade-from-repo
spec:
  params:
  - description: Specify a specific helm repo
    name: helmRepo
    type: string
  - description: Username
    name: username
    type: string
  - description: Pass
    name: password
    type: string
  - description: Specify chart name that will be deployed
    name: chartName
    type: string
  - default: v1.0.0
    description: The helm release version in semantic versioning format
    name: releaseVersion
    type: string
  - default: helmRelease
    description: The helm release name
    name: releaseName
    type: string
  - default: ""
    description: The helm release namespace
    name: releaseNamespace
    type: string
  - default: ""
    description: 'Specify the values you want to overwrite, comma separated: autoscaling.enabled=true,replicas=1'
    name: overwriteValues
    type: string
  - default: latest
    description: Specify a specific helm version
    name: helmVersion
    type: string
  - default: dev
    description: Specify what env to use for values
    name: env
    type: string
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - image: lachlanevenson/k8s-helm:$(inputs.params.helmVersion)
    name: upgrade-from-repo
    resources: {}
    script: |
      echo "setting HELM_EXPERIMENTAL_OCI=1"
      export HELM_EXPERIMENTAL_OCI=1
      echo "logging in to helm repo"
      helm registry login "$(inputs.params.helmRepo)" --username "$(inputs.params.username)" --password "$(inputs.params.password)"
      echo "pulling chart to local repo"
      helm chart pull "$(inputs.params.helmRepo)"/"$(inputs.params.chartName)":v1
      echo "exporting helm chart"
      helm chart export "$(inputs.params.helmRepo)"/"$(inputs.params.chartName)":v1 --destination .
      echo "installing helm chart"
      helm upgrade --install ocp-openjdk ./"$(inputs.params.chartName)" -f ./ocp/"$(inputs.params.env)".yaml --namespace "$(inputs.params.releaseNamespace)" --set "$(inputs.params.overwriteValues)"
    workingDir: /workspace/source
